import prettier from 'eslint-config-prettier';
import path from 'node:path';
import js from '@eslint/js';
import svelte from 'eslint-plugin-svelte';
import { defineConfig, includeIgnoreFile } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	js.configs.recommended,
	ts.configs.recommended,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: { globals: { ...globals.browser, ...globals.node } },
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser
			}
		}
	},
	{
		rules: {
			// This app is served from the root of its own origin, and the rule also
			// fires on shadcn-svelte's own components. Plain hrefs are correct here.
			'svelte/no-navigation-without-resolve': 'off',

			// A great many of this codebase's Maps and Sets are deliberately NOT
			// reactive: pointer-id tracking in hot input handlers, the monitor's
			// per-frame filter sets, bus subscriber lists. Making them reactive
			// would add overhead for state nothing renders. Where reactivity is
			// wanted, `$state` reassignment is used explicitly.
			'svelte/prefer-svelte-reactivity': 'off'
		}
	},
	{
		// The only {@html} in the codebase. `highlight()` HTML-escapes &, < and >
		// before inserting its own <span> wrappers, so editor contents can never
		// become markup — but the rule cannot see that.
		files: ['src/lib/components/midi/CodeSandbox.svelte'],
		rules: { 'svelte/no-at-html-tags': 'off' }
	},
	{
		// Generated by the shadcn-svelte CLI; not ours to lint.
		files: ['src/lib/components/ui/**'],
		rules: {
			'@typescript-eslint/no-unused-vars': 'off',
			'svelte/no-at-html-tags': 'off'
		}
	}
);
