/** Static lesson objectives: mounting and navigation never change the denominator. */
export const CHECKPOINTS: Record<string, readonly string[]> = {
	aftertouch: ['channel-at', 'poly-at', 'poly-two', 'reset'],
	'building-a-sequencer': ['pattern', 'export', 'code', 'clean-stop'],
	'bytes-and-bits': ['ch10', 'cc-status', 'four-types', 'max-velocity'],
	capstone: [
		'connected',
		'two-destinations',
		'clock',
		'patch',
		'automate',
		'break',
		'recover',
		'document'
	],
	channels: ['ch4', 'drums', 'three-channels', 'ch16'],
	'control-change': ['cc74', 'sweep', 'four-ccs', 'while-held'],
	'control-not-sound': ['play-note', 'two-voices', 'five-notes'],
	'device-profiles': ['create', 'param', 'drive', 'learn'],
	envelope: ['attack', 'release', 'then-play'],
	'how-midi-happened': ['grammy', 'bitrate', 'read'],
	'in-out-thru': ['thru', 'count', 'local'],
	'in-the-daw': ['inspect', 'velocity-range', 'automate', 'learn'],
	'inside-the-instrument': ['cutoff', 'resonance', 'sweep', 'architectures'],
	'just-enough-music': ['fifth', 'major', 'minor', 'octave'],
	'latency-and-jitter': ['naive', 'lookahead', 'measure'],
	'midi-2': ['ump', 'resolution', 'decide'],
	'midi-clock': ['run', 'clock-out', 'spp', 'continue', 'tempo'],
	'midi-files': ['vlq', 'open', 'play', 'write'],
	mpe: ['configure', 'member', 'per-note-bend', 'slide'],
	'notation-and-midi': ['enharmonic', 'chord', 'choose'],
	'note-on-off': ['pair', 'stick', 'rescue', 'long-note'],
	'notes-and-pitch': ['middle-c', 'octave', 'triad', 'octave-span'],
	panic: ['notes-off', 'sound-off', 'pedal-trap', 'local', 'silence'],
	patterns: ['euclid', 'play', 'alternate', 'polyrhythm'],
	'pitch-bend': ['up', 'down', 'centre', 'range', 'chord-bend'],
	'ppqn-and-groove': ['play', 'swing', 'distinguish'],
	'programming-drums': ['kick', 'kit', 'dynamics', 'flam'],
	'programs-and-banks': ['pc', 'high-program', 'bank-sequence', 'explore'],
	'rpn-nrpn': ['select', 'rpn00', 'nrpn', 'fine', 'null'],
	'studio-routing': ['route', 'remap', 'split', 'plan'],
	'sync-options': ['mtc', 'policy', 'explain'],
	sysex: ['build', 'identity', 'universal', 'permission'],
	transports: ['pins', 'trs', 'ports', 'host'],
	troubleshooting: ['tree', 'count', 'chart'],
	tuning: ['hear', 'rpn-tune', 'detune', 'bend-cents'],
	velocity: ['soft', 'hard', 'range'],
	'web-audio': ['voice', 'clocks', 'midi-synth', 'envelope'],
	'web-midi': ['list', 'raw', 'receive', 'scheduled'],
	'pulse-and-rhythm': ['pulse', 'rests', 'apply'],
	'pitch-and-melody': ['steps', 'melody', 'apply'],
	'chords-and-movement': ['triad', 'inversion', 'apply'],
	'bass-and-drums': ['drums', 'bass', 'apply'],
	'musical-expression': ['dynamics', 'space', 'apply'],
	'first-composition': ['apply']
};
